services:
  - type: web
    name: coinbase-clone-api
    runtime: node
    buildCommand: npm --prefix server install
    startCommand: npm --prefix server start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # Set this in Render dashboard
      - key: JWT_SECRET
        sync: false # Set this in Render dashboard
      - key: CLIENT_URL
        value: https://agudu-coinbase-clone1.netlify.app/
